name: "Deploy"
description: "Deploy using Docker and docker-compose"
inputs:
  docker-image-name:
    description: "Docker Image Name"
    required: true
  docker-compose-file:
    description: "Docker Compose File"
    required: true
  docker-env-vars:
    description: "Docker Environment Variables"
    required: true
  ssh-host:
    description: "SSH Host"
    required: true
  ssh-user:
    description: "SSH User"
    required: true
  ssh-private-key:
    description: "SSH Private Key"
    required: true
  working-directory:
    description: "Optional working directory"
    required: false
    default: ./
runs:
  using: "composite"
  steps:
    - id: create-local-ssh-folder
      run: mkdir -p ~/.ssh
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: prepare-ssh-key
      run: |
        echo "${{ inputs.ssh-private-key }}" | sed '/^$/d' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: add-known-host
      run: ssh -oStrictHostKeyChecking=accept-new ${{ inputs.ssh-user }}@${{ inputs.ssh-host }} echo Connection to ${{ inputs.ssh-host }} successful
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: create-remote-folder
      run: ssh ${{ inputs.ssh-user }}@${{ inputs.ssh-host }} mkdir -p /tmp/deploy-action/${{ inputs.docker-image-name }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: scp-docker-compose-file
      run: "scp ${{ inputs.docker-compose-file }} ${{ inputs.ssh-user }}@${{ inputs.ssh-host }}:/tmp/deploy-action/${{ inputs.docker-image-name }}/docker-compose.yml"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: create-docker-env-file
      run: |
        ssh ${{ inputs.ssh-user }}@${{ inputs.ssh-host }} "cat <<EOF > /tmp/deploy-action/${{ inputs.docker-image-name }}/env.prod
        ${{ inputs.docker-env-vars }}
        EOF"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: docker-pull-latest
      run: ssh ${{ inputs.ssh-user }}@${{ inputs.ssh-host }} docker pull ghcr.io/${{ github.repository }}/${{ inputs.docker-image-name }}:latest
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: docker-compose-up
      run: ssh ${{ inputs.ssh-user }}@${{ inputs.ssh-host }} "cd /tmp/deploy-action/${{ inputs.docker-image-name }} && IMAGE_TAG=latest docker-compose -f docker-compose.yml up -d"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: remove-remote-folder
      run: ssh ${{ inputs.ssh-user }}@${{ inputs.ssh-host }} rm -rf /tmp/deploy-action/${{ inputs.docker-image-name }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: docker-system-prune
      run: ssh ${{ inputs.ssh-user }}@${{ inputs.ssh-host }} docker system prune -f
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: remove-ssh-folder
      run: rm -rf ~/.ssh
      shell: bash
      working-directory: ${{ inputs.working-directory }}
